"""Configuration objects and helpers for the model validation tool."""

from __future__ import annotations

import ast
import os
import os.path as osp
from dataclasses import asdict, dataclass, field, fields
from typing import Any, Dict, List, Optional, Tuple

import cv2
import numpy as np

MULTIPLIER_MODE = "multiplier"
RATIO_MODE = "ratio"
COUNT_MODE = "count"
AUGMENT_MODES = (MULTIPLIER_MODE, RATIO_MODE, COUNT_MODE)

# The one source of the shipped amount ratio: the ValidationConfig
# field and the default of the count planner read this name, and the
# configuration page shows it in the r control, so the default is
# changed here and nowhere else. The shipped value augments with
# round(n * ratio) copies drawn from the n valid originals at random.
DEFAULT_RATIO = 0.5

MULTI_IMAGE_AUGMENTATIONS = (
    "mosaic",
    "mixup",
    "cutmix",
    "copy_paste",
    "copy_paste_mode",
    "auto_augment",
)

# How the canvas area a geometric transform uncovers is filled is no
# longer an option: the fill is pure black and nothing else. A fixed
# black band is what the user asked for by name, because it is what the
# downstream tooling expects. Replicating the border pixels smears the
# outermost row and column of the picture into stripes as soon as a
# translation or a zoom exposes new canvas, and the mirrored reflection
# invents a structure that is not in the picture either - both are
# exactly the artefact an anomaly detection run must not be handed,
# therefore neither is reachable any more: augment.build_transforms
# pins cv2.BORDER_CONSTANT plus augment.BLACK_FILL on Affine and on
# Perspective alike.
#
# The one value that fill carries for the snapshot of a run: every channel
# of every filled pixel is black. The spelling lives here, so that the
# report states what the copies were built with without importing the
# transform stack.
BORDER_FILL = "black"

# The two CPU bound stages of the tool - the generation of the augmented
# copies and the inference - run the very same, fixed amount of parallel
# workers: half of the logical processors of the machine the tool runs
# on, never below one. A 22 logical core machine therefore runs 11
# workers, an 8 core one 4, a 4 core one 2, and a 2 core (or a single
# core) one a single worker. The amount is derived at run time and is
# deliberately not configurable any more: the configuration page only
# displays it, and every stored configuration resolves back to it.
#
# The copies are generated by a pool of threads: Albumentations hands
# the heavy geometric, colour and encoding kernels to OpenCV and NumPy,
# which release the GIL, therefore a pool of threads really overlaps the
# work while a process pool would only add the cost of serialising every
# image and every label.


def logical_cores(cpu_count: Any = None) -> int:
    """Return the amount of logical processors of the machine.

    A machine that does not report its processor count (os.cpu_count()
    answers None) counts as a single processor, so every value derived
    from this helper stays usable. ``cpu_count`` overrides the machine
    value for the callers that already know it.
    """

    cores = os.cpu_count() if cpu_count is None else cpu_count
    try:
        cores = int(cores)
    except (TypeError, ValueError):
        cores = 1
    return max(1, cores)


def default_workers(cpu_count: Any = None) -> int:
    """Return the fixed worker count shared by both stages.

    Half of the logical processors, never below one: this is the single
    source of the concurrency of the augment pool and of the inference
    session pool, so that the two formulas can never drift apart.
    """

    return max(1, logical_cores(cpu_count) // 2)


DEFAULT_WORKERS = default_workers()
DEFAULT_AUGMENT_WORKERS = DEFAULT_WORKERS
DEFAULT_INFER_WORKERS = DEFAULT_WORKERS
# The fixed count is also the upper bound of the two clamps below and
# both stages read it from :func:`default_workers` itself; these two
# names mirror it for the callers that still import them.
AUGMENT_WORKERS_LIMIT = DEFAULT_WORKERS
INFER_WORKERS_LIMIT = DEFAULT_WORKERS


def resolve_augment_workers(value: Any = None) -> int:
    """Clamp a stored worker count into [1, default_workers()].

    The configuration page no longer exposes the control and the
    augment stage reads the fixed count of :func:`default_workers`
    itself, therefore the stored field of a configuration never drives
    the pool any more. The guard stays for the callers that still hand
    a value over: a missing or unreadable one falls back to the fixed
    count, and no value can turn the stage off (0, a negative value) or
    push it beyond the count the machine was derived for.
    """

    limit = default_workers()
    try:
        count = int(value)
    except (TypeError, ValueError):
        return limit
    return max(1, min(limit, count))


# The exported detector has a static batch of one - ONNX Runtime refuses
# any other batch - therefore the inference stage cannot group the
# images: the only way to use more than one core is to run several
# sessions side by side, every one of them on its own thread. The stage
# runs the very same fixed count as the augment stage.
#
# The per session budget below is what keeps the sessions from fighting
# for the cores. Measured on a 22 logical core / 16 physical core
# machine (YOLO11s detect 640, ONNX Runtime 1.30 CPU, the first 320
# samples of the real 683 pair dataset, best of two):
#   1 session  (runtime default)   28.3 s   11.30 img/s   1.00x   445 MB
#   2 sessions (11 threads each)   30.0 s   10.66 img/s   0.94x   665 MB
#   3 sessions ( 7 threads each)   23.2 s   13.78 img/s   1.22x   865 MB
#   4 sessions ( 5 threads each)   22.2 s   14.40 img/s   1.27x  1056 MB
#   6 sessions ( 3 threads each)   20.9 s   15.29 img/s   1.35x  1456 MB
# Eight sessions (2 threads each) are slower again than four, and a
# session left with the runtime default oversubscribes the machine:
# four of them measured 212.7 ms per image against 88.5 for a single
# one (0.42x). With the fixed count the machine is split evenly: on a
# 22 core machine eleven sessions keep max(1, 22 // 11) = 2 threads.


def resolve_infer_workers(value: Any = None) -> int:
    """Clamp a stored session count into [1, default_workers()].

    The configuration page no longer exposes the control and the
    inference stage reads the fixed count of :func:`default_workers`
    itself, therefore the stored field of a configuration never drives
    the pool any more. The guard stays for the callers that still hand
    a value over: a missing or unreadable one falls back to the fixed
    count, and no value can turn the stage off (0, a negative value) or
    spawn more sessions than the machine was derived for.
    """

    limit = default_workers()
    try:
        count = int(value)
    except (TypeError, ValueError):
        return limit
    return max(1, min(limit, count))


def infer_session_threads(cpu_count: Any = None) -> Tuple[int, int]:
    """Return the (intra_op, inter_op) thread budget of one session.

    ONNX Runtime hands every session the whole machine unless it is told
    otherwise: running N of them with the default options makes the
    sessions fight for the cores and they end up as slow as a single
    one. Each parallel session therefore keeps its own slice of the CPUs
    (max(1, cpu // N) intra-op threads) and a single inter-op thread,
    because the graph of a YOLO detector is a chain and never benefits
    from running several operators at once. N is the fixed session count
    of :func:`default_workers`: a 22 logical core machine runs eleven
    sessions of max(1, 22 // 11) = 2 threads each.

    A single session has nothing to share with anybody, so it keeps the
    default of the runtime instead (both counts are 0, which is the
    documented "let the runtime decide" value). Measured on a 22 logical
    / 16 physical core machine, that default is 1.7x faster than pinning
    the only session to all 22 logical cores: an intra-op pool larger
    than the physical core count only spins. That is the state of a
    machine derived for a single session (one or two logical cores).
    """

    cores = logical_cores(cpu_count)
    sessions = default_workers(cores)
    if sessions <= 1:
        return 0, 0
    return max(1, cores // sessions), 1


def infer_threads_snapshot() -> Dict[str, Any]:
    """Return the JSON friendly thread parameters of one session."""

    intra, inter = infer_session_threads()
    return {
        "workers": default_workers(),
        "intra_op_threads": intra,
        "inter_op_threads": inter,
        # 0 is the "let the runtime decide" value of ONNX Runtime, used
        # by the single session configuration.
        "runtime_default_threads": intra == 0,
        "cpu_count": logical_cores(),
    }


# Both stages hand their decode, resize, transform and encode kernels to
# the thread pool of OpenCV. The fixed concurrency already fills the
# machine, therefore every thread of a parallel pool pins that pool to a
# single thread before it takes its first job: OpenCV would otherwise
# start its own pool inside every worker and oversubscribe the CPUs
# (measured on 22 logical cores, the pinning alone made the augment
# stage 16 percent faster). The serial path keeps the default of the
# runtime, it has nothing to share.
OPENCV_THREADS = 1


def limit_opencv_threads(count: int = OPENCV_THREADS) -> None:
    """Pin the OpenCV thread pool, called inside a parallel worker."""

    cv2.setNumThreads(int(count))


class ValidationConfigError(ValueError):
    """Raised when the user supplied validation options are invalid."""


@dataclass
class AugmentParams:
    """Single image augmentation parameters.

    Every field name matches the official Ultralytics augmentation
    argument name so that the configuration snapshot can be compared
    1:1 with a training YAML.
    """

    # The shipped values: a mild geometric augmentation (a rotation and a
    # shear of a few degrees, a zoom in, both flips at a low probability)
    # around the constant pure black fill. The configuration page reads
    # every one of them from this dataclass, so a default is edited here
    # only.
    hsv_h: float = 0.015
    hsv_s: float = 0.7
    hsv_v: float = 0.4
    degrees: float = 15.0
    translate: float = 0.1
    scale_min: float = 0.8
    scale_max: float = 1.5
    shear: float = 10.0
    perspective: float = 0.0
    flipud: float = 0.2
    fliplr: float = 0.2
    bgr: float = 0.0
    erasing: float = 0.4
    crop_fraction: float = 1.0
    seed: int = 0
    # The fill of the canvas uncovered by Affine / Perspective is not a
    # parameter any more: build_transforms pins the constant border mode and
    # the black fill below on both geometric transforms. It is no official
    # Ultralytics argument, therefore the snapshot records the one value of
    # the run under its own border_fill key, outside official_names.

    def to_official_dict(self) -> Dict[str, Any]:
        """Return the parameters using the official argument names."""

        scale: Any = self.scale_min
        if abs(self.scale_max - self.scale_min) > 1e-9:
            scale = [self.scale_min, self.scale_max]
        return {
            "hsv_h": self.hsv_h,
            "hsv_s": self.hsv_s,
            "hsv_v": self.hsv_v,
            "degrees": self.degrees,
            "translate": self.translate,
            "scale": scale,
            "shear": self.shear,
            "perspective": self.perspective,
            "flipud": self.flipud,
            "fliplr": self.fliplr,
            "bgr": self.bgr,
            "erasing": self.erasing,
            "crop_fraction": self.crop_fraction,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AugmentParams":
        """Build parameters from a possibly partial mapping."""

        known = {item.name for item in fields(cls)}
        payload = {k: v for k, v in data.items() if k in known}
        return cls(**payload)

    def snapshot(self) -> Dict[str, Any]:
        """Return a JSON friendly snapshot of the parameters."""

        data = asdict(self)
        data["scale"] = [self.scale_min, self.scale_max]
        # The fill of the uncovered canvas has no option any more: the one
        # value the stack applies is recorded here, so a report still says
        # what the copies were built with.
        data["border_fill"] = BORDER_FILL
        data["official_names"] = self.to_official_dict()
        data["disabled_multi_image_augmentations"] = list(
            MULTI_IMAGE_AUGMENTATIONS
        )
        data["not_applied"] = ["erasing", "crop_fraction"]
        return data


@dataclass
class ValidationConfig:
    """Options collected on the configuration page."""

    dataset_dir: str = ""
    classes_file: str = ""
    model_path: str = ""
    # The three verdict thresholds: the confidence cut keeps the boxes
    # the interface was tuned to, the two IoU values stay where they are.
    conf_threshold: float = 0.5
    iou_threshold: float = 0.45
    ng_iou_threshold: float = 0.5
    judge_augmented: bool = True
    augment_enabled: bool = True
    augment_mode: str = RATIO_MODE
    multiplier: int = 1
    ratio: float = DEFAULT_RATIO
    total_count: int = 0
    augment_params: AugmentParams = field(default_factory=AugmentParams)
    # Fixed concurrency of both CPU bound stages: the pool of threads
    # generating the augmented copies and the amount of independent ONNX
    # sessions running the inference share the one value derived from the
    # logical processors of the machine by default_workers(), and both
    # stages read that function themselves. The two fields hold the very
    # same value (the configuration page only displays it) and they stay
    # so that a stored configuration and the report snapshot keep their
    # shape; one worker is the serial behaviour, and the count never
    # changes a produced byte nor a verdict, only the duration. Every
    # inference session is pinned to its own slice of the CPUs,
    # otherwise the sessions over-subscribe the machine.
    augment_workers: int = DEFAULT_AUGMENT_WORKERS
    infer_workers: int = DEFAULT_INFER_WORKERS

    def to_dict(self) -> Dict[str, Any]:
        """Return a JSON friendly snapshot of the configuration."""

        return {
            "dataset_dir_display": self.dataset_dir,
            "classes_file": self.classes_file,
            "model_path": self.model_path,
            "conf_threshold": self.conf_threshold,
            "iou_threshold": self.iou_threshold,
            "ng_iou_threshold": self.ng_iou_threshold,
            "judge_augmented": self.judge_augmented,
            "augment_enabled": self.augment_enabled,
            "augment_mode": self.augment_mode,
            "multiplier": self.multiplier,
            "ratio": self.ratio,
            "total_count": self.total_count,
            "augment_workers": self.augment_workers,
            "augment_workers_default": DEFAULT_AUGMENT_WORKERS,
            "augment_params": self.augment_params.snapshot(),
            "infer_workers": self.infer_workers,
            "infer_workers_default": DEFAULT_INFER_WORKERS,
            "infer_session_threads": infer_threads_snapshot(),
            "workers_fixed": True,
            "workers_rule": "max(1, os.cpu_count() // 2)",
        }


def load_classes_file(path: str) -> List[str]:
    """Load a classes.txt file.

    Blank lines are removed and the remaining order defines the class
    ids. Repeated class names are rejected because the model metadata
    contract requires an unambiguous 1:1 mapping.
    """

    if not path or not osp.isfile(path):
        raise ValidationConfigError(f"Classes file not found: {path}")
    with open(path, "r", encoding="utf-8-sig") as handle:
        raw_lines = handle.read().splitlines()

    names = [line.strip() for line in raw_lines]
    names = [name for name in names if name]
    if not names:
        raise ValidationConfigError(f"Classes file is empty: {path}")

    seen: Dict[str, int] = {}
    duplicates: List[str] = []
    for index, name in enumerate(names):
        if name in seen:
            duplicates.append(f"{name} (#{seen[name]} and #{index})")
        else:
            seen[name] = index
    if duplicates:
        raise ValidationConfigError(
            "Duplicated class names in classes file: " + ", ".join(duplicates)
        )
    return names


def plan_aug_counts(
    sample_count: int,
    mode: str,
    multiplier: int = 1,
    ratio: float = DEFAULT_RATIO,
    total: int = 0,
    rng: Any = None,
) -> List[int]:
    """Return how many augmented copies each original image receives.

    MULTIPLIER_MODE gives every image exactly k copies, RATIO_MODE
    keeps only the total round(n * r) and draws the sources from the
    originals (with replacement when a generator is given) while
    COUNT_MODE distributes the total deterministically: base, plus one
    for the first remainder images. RATIO_MODE is the default of the
    configuration page.
    """

    if sample_count < 0:
        raise ValidationConfigError("sample_count must not be negative")
    if sample_count == 0:
        raise ValidationConfigError(
            "No original image to augment (sample_count is 0)"
        )
    if mode == MULTIPLIER_MODE:
        if multiplier < 0:
            raise ValidationConfigError(
                f"multiplier must not be negative, got {multiplier}"
            )
        return [int(multiplier)] * sample_count
    if mode == RATIO_MODE:
        value = float(ratio)
        if not 0 <= value <= 10:
            raise ValidationConfigError(
                f"ratio must be within [0, 10], got {value}"
            )
        count = int(round(sample_count * value))
        if rng is None:
            # Without a generator the copies are spread deterministically:
            # the result always has one entry per original image.
            base, remainder = divmod(count, sample_count)
            return [
                base + (1 if index < remainder else 0)
                for index in range(sample_count)
            ]
        indices = [int(i) for i in rng.integers(0, sample_count, size=count)]
        return [indices.count(i) for i in range(sample_count)]
    if mode == COUNT_MODE:
        if total < 0:
            raise ValidationConfigError(
                f"Augment count must not be negative, got {total}"
            )
        base, remainder = divmod(int(total), sample_count)
        return [
            base + (1 if index < remainder else 0)
            for index in range(sample_count)
        ]
    raise ValidationConfigError(f"Unsupported augment mode: {mode}")


def validate_augment_params(params: AugmentParams) -> None:
    """Validate augmentation parameter ranges."""

    ranges = {
        "hsv_h": (0.0, 1.0),
        "hsv_s": (0.0, 1.0),
        "hsv_v": (0.0, 1.0),
        "degrees": (0.0, 180.0),
        "translate": (0.0, 1.0),
        "scale_min": (0.0, 10.0),
        "scale_max": (0.0, 10.0),
        "shear": (0.0, 180.0),
        "perspective": (0.0, 0.001),
        "flipud": (0.0, 1.0),
        "fliplr": (0.0, 1.0),
        "bgr": (0.0, 1.0),
        "erasing": (0.0, 1.0),
        "crop_fraction": (0.0, 1.0),
    }
    for name, (low, high) in ranges.items():
        value = float(getattr(params, name))
        if not low - 1e-9 <= value <= high + 1e-9:
            raise ValidationConfigError(
                f"Augmentation parameter {name} must be within "
                f"[{low}, {high}], got {value}"
            )
    if params.scale_min > params.scale_max:
        raise ValidationConfigError(
            "scale min must not be greater than scale max "
            f"({params.scale_min} > {params.scale_max})"
        )


def border_fill_value(image: Any) -> Optional[Tuple[float, ...]]:
    """Return the median of an image, one value per channel.

    UNUSED by the pipeline: the uncovered canvas is filled with pure
    black (augment.BLACK_FILL), never with a value derived from the
    picture, therefore nothing calls this helper any more. It stays
    exported so that a caller that really wants the median of a picture
    still has one place to read it from.

    The median is computed on the image as it is handed in, so a colour
    image gets one median per channel and a single channel image one
    scalar. Returns None for an empty image, the caller then keeps the
    albumentations default of the transform.
    """

    if image is None:
        return None
    array = np.asarray(image)
    if array.size == 0 or array.ndim < 2:
        return None
    if array.ndim == 2:
        return (float(np.median(array)),)
    medians = np.median(array, axis=(0, 1))
    return tuple(float(value) for value in np.ravel(medians))


def derive_seed(base_seed: int, index: int) -> int:
    """Derive a stable sub-seed for one sample.

    Albumentations 2.x exposes a set_random_seed API instead of
    accepting a numpy Generator, therefore per sample reproducibility
    is achieved by deriving an integer seed from the base seed and the
    sample index.
    """

    sequence = (int(base_seed) + 0x9E3779B9 * int(index)) % (2**63)
    return int(sequence)


# One sample may be generated more than once: the first try keeps the
# seed of the sample itself and every retry folds its own attempt number
# into the derivation input. The stride keeps the retry input of one
# sample away from the sample indices the pipeline builds (the pipeline
# numbers the samples sample * 1000 + copy).
ATTEMPT_INDEX_STRIDE = 1000


def attempt_seed(base_seed: int, sample_index: int, attempt: int) -> int:
    """Derive the stable sub-seed of one attempt of one sample.

    Attempt 0 returns the very seed the sample always had - the one
    derive_seed(base_seed, sample_index) handed out before the retry loop
    existed - so a first try reproduces the historical bytes exactly.
    Every retry folds its own attempt number into the derivation input
    instead, therefore the seed of an attempt is a function of (base
    seed, sample index, attempt) alone: the same configuration reproduces
    the same output whatever the number of threads and whatever the order
    the samples happen to finish in.

    The two inputs cannot collide: sample * 1000 + attempt stays below
    2**63 for every real sample index and only a difference of a whole
    multiple of 2**63 could make the two derivations agree.
    """

    if int(attempt) <= 0:
        return derive_seed(base_seed, int(sample_index))
    combined = int(sample_index) * ATTEMPT_INDEX_STRIDE + int(attempt)
    return derive_seed(base_seed, combined)


def make_rng(base_seed: int, index: int = 0) -> Any:
    """Return a seeded numpy random generator for one sample."""

    import numpy as np

    return np.random.default_rng([int(base_seed), int(index)])


def parse_names_literal(value: str) -> List[str]:
    """Parse the Ultralytics names metadata value."""

    try:
        parsed = ast.literal_eval(value)
    except (ValueError, SyntaxError) as error:
        raise ValidationConfigError(
            f"Invalid ONNX names metadata: {value!r} ({error})"
        ) from error
    if isinstance(parsed, dict):
        try:
            ordered = sorted(parsed.items(), key=lambda item: int(item[0]))
        except (TypeError, ValueError) as error:
            raise ValidationConfigError(
                f"Invalid ONNX names metadata keys: {value!r}"
            ) from error
        return [str(name) for _, name in ordered]
    if isinstance(parsed, (list, tuple)):
        return [str(name) for name in parsed]
    raise ValidationConfigError(f"Unsupported ONNX names: {value!r}")


def parse_imgsz_literal(value: str) -> List[int]:
    """Parse the Ultralytics imgsz metadata value."""

    try:
        parsed = ast.literal_eval(value)
    except (ValueError, SyntaxError) as error:
        raise ValidationConfigError(
            f"Invalid ONNX imgsz metadata: {value!r} ({error})"
        ) from error
    if isinstance(parsed, int):
        return [int(parsed), int(parsed)]
    if isinstance(parsed, (list, tuple)) and len(parsed) >= 2:
        return [int(parsed[0]), int(parsed[1])]
    raise ValidationConfigError(f"Unsupported ONNX imgsz: {value!r}")


def is_int_dimension(value: Any) -> bool:
    """Return True when an ONNX input dimension is a static integer."""

    if isinstance(value, bool):
        return False
    return isinstance(value, int) and value > 0


__all__ = [
    "ATTEMPT_INDEX_STRIDE",
    "AUGMENT_MODES",
    "AUGMENT_WORKERS_LIMIT",
    "BORDER_FILL",
    "COUNT_MODE",
    "DEFAULT_AUGMENT_WORKERS",
    "DEFAULT_INFER_WORKERS",
    "DEFAULT_RATIO",
    "DEFAULT_WORKERS",
    "INFER_WORKERS_LIMIT",
    "MULTIPLIER_MODE",
    "MULTI_IMAGE_AUGMENTATIONS",
    "OPENCV_THREADS",
    "RATIO_MODE",
    "AugmentParams",
    "ValidationConfig",
    "ValidationConfigError",
    "attempt_seed",
    "border_fill_value",
    "default_workers",
    "derive_seed",
    "infer_session_threads",
    "infer_threads_snapshot",
    "is_int_dimension",
    "limit_opencv_threads",
    "load_classes_file",
    "logical_cores",
    "make_rng",
    "parse_imgsz_literal",
    "parse_names_literal",
    "plan_aug_counts",
    "resolve_augment_workers",
    "resolve_infer_workers",
    "validate_augment_params",
]
