"""Three stage validation worker (staging, augment, infer + judge).

The worker runs in a QThread like the existing batch processing helper
of the repository. Every record is isolated: a failure on one image
produces an INFER_ERROR verdict instead of aborting the whole run.

The augmented copies of the second stage are independent of each other
and are generated by a pool of worker threads. A sample is fully
described by its own seed and its own output paths, therefore the
produced bytes never depend on the number of threads nor on the order
in which the samples happen to finish.
"""

from __future__ import annotations

import os
import os.path as osp
import threading
import traceback
from concurrent.futures import FIRST_COMPLETED, Future, ThreadPoolExecutor
from concurrent.futures import wait as wait_futures
from dataclasses import dataclass, field
from queue import SimpleQueue
from typing import Any, Dict, Iterator, List, Optional, Tuple

from PyQt6.QtCore import QThread, pyqtSignal

from . import dataset
from . import records as records_module
from .app_config import (
    RATIO_MODE as DEFAULT_AUGMENT_MODE,
    BORDER_FILL,
    DEFAULT_RATIO,
    MULTI_IMAGE_AUGMENTATIONS,
    ValidationConfig,
    ValidationConfigError,
    default_workers,
    limit_opencv_threads,
    plan_aug_counts,
    validate_augment_params,
)
from .judge import judge_record, shape_label, shape_type_of
from .multilabel import expand_multilabel_rows
from .records import ValidationRecord

STAGE_STAGING = "staging"
STAGE_AUGMENT = "augment"
STAGE_INFER = "infer"

# How many dropped samples the augment summary lists one by one: the
# counter is the source of truth for the numbers, the list only names
# the first few so that a run against an unfittable dataset cannot grow
# the report without a bound.
DISCARDED_SAMPLE_LIMIT = 50
DISCARDED_NOTE = (
    "one sample per planned copy is generated again with a fresh derived "
    "seed while a transform leaves a shape outside the picture and is "
    "dropped when no attempt fits; discarded_unfittable is the count of "
    "the dropped ones, the discarded list names at most "
    f"{DISCARDED_SAMPLE_LIMIT} of them"
)


def _opencv_initializer(workers: int) -> Optional[Any]:
    """Return what pins OpenCV inside every thread of a parallel pool.

    The initializer of a thread pool runs at the start of a worker
    thread, before its first job, which is the very moment that thread
    decides how many OpenCV threads its decode, transform and encode
    calls may start: the fixed concurrency already fills the machine,
    so every parallel worker keeps that pool at one thread. The serial
    path - a single worker - returns None and keeps the default of the
    runtime, it has nothing to share.
    """

    if int(workers) > 1:
        return limit_opencv_threads
    return None


@dataclass
class _InferJob:
    """One staged image waiting for an inference worker."""

    ordinal: int
    record: ValidationRecord


@dataclass
class _InferJobResult:
    """What one inference worker produced for a single image.

    A broken image stays a result like any other: its message becomes
    the INFER_ERROR verdict of its own record and never travels back
    into the stage loop, so one undecodable file can never fail a run.
    """

    job: _InferJob
    verdict: str = ""
    reasons: List[str] = field(default_factory=list)
    detail: Dict[str, Any] = field(default_factory=dict)


@dataclass
class _AugmentJob:
    """One augmented copy waiting for a worker thread."""

    ordinal: int
    record: ValidationRecord
    sample_index: int
    copy_index: int
    image_name: str
    source_ext: str


@dataclass
class _AugmentJobResult:
    """What one worker thread produced for a single job.

    A broken sample stays a result: its exception is reported as a
    warning and counted, it never travels back into the stage loop. A
    sample no seed could fit does the same through the discarded flag.
    """

    job: _AugmentJob
    child: Optional[ValidationRecord] = None
    warnings: List[str] = field(default_factory=list)
    encode_fallback: bool = False
    clipped: List[Dict[str, Any]] = field(default_factory=list)
    type_counts: Dict[str, int] = field(default_factory=dict)
    # the source image held gray content: the sample travelled through
    # the gray -> RGB -> gray path of augment_sample
    grayscale: bool = False
    # how many tries augment_sample needed, and how many tries the whole
    # stage spent: a dropped sample reports its spent attempts as well
    attempts: int = 0
    discarded: bool = False


class ValidationWorker(QThread):
    """Run the complete validation pipeline inside a worker thread."""

    progress = pyqtSignal(str, int, int, str)
    stage_finished = pyqtSignal(str, int)
    # non blocking notes of the run (metadata hints, skipped files): they
    # reach the log of the progress page and the validation report.
    warnings_ready = pyqtSignal(list)
    dataset_ready = pyqtSignal(str, list, dict)
    failed = pyqtSignal(str, str)
    # a cancelled run is an outcome of its own: it never travels through
    # the failure path, so the window can drop the whole run instead of
    # reporting an error
    cancelled = pyqtSignal()
    finished_ok = pyqtSignal()

    def __init__(
        self,
        config: ValidationConfig,
        classes: List[str],
        staging_root: str,
        parent: Optional[Any] = None,
    ) -> None:
        super().__init__(parent)
        self.config = config
        self.classes = list(classes)
        self.staging_root = staging_root
        self.cancel_requested = False
        self.records: List[ValidationRecord] = []
        self.model_info: Dict[str, Any] = {}
        self.augment_summary: Dict[str, Any] = {}
        # effective parameters of the inference stage (session count and
        # the thread budget pinned on every session), for the report.
        self.infer_summary: Dict[str, Any] = {}
        self.warnings: List[str] = []

    def cancel(self) -> None:
        """Request a cooperative cancellation of the running pipeline."""

        self.cancel_requested = True

    def run(self) -> None:
        """Execute the three pipeline stages."""

        try:
            self._stage_staging()
            if self.cancel_requested:
                self._emit_cancelled()
                return
            self._stage_augment()
            if self.cancel_requested:
                self._emit_cancelled()
                return
            self._stage_infer()
            if self.cancel_requested:
                # the last stage can be cancelled as well: a run that was
                # stopped never reports itself as finished
                self._emit_cancelled()
                return
            self.finished_ok.emit()
        except ValidationConfigError as error:
            self.failed.emit("Configuration error", str(error))
        except Exception as error:  # noqa: BLE001
            detail = traceback.format_exc()
            self.failed.emit("Validation failed", f"{error}\n{detail}")

    def _emit_warnings(self, warnings: Optional[Any] = None) -> None:
        """Publish the non blocking notes of the current stage."""

        items = [str(item) for item in (warnings or [])]
        if items:
            self.warnings_ready.emit(items)

    def _emit_cancelled(self) -> None:
        """Report a cancelled run."""

        self.cancelled.emit()

    def _progress(
        self, stage: str, done: int, total: int, message: str
    ) -> None:
        """Emit a progress update."""

        self.progress.emit(stage, int(done), int(total), message)

    def _stage_staging(self) -> None:
        """Copy the source dataset into staging once, read only."""

        self._progress(STAGE_STAGING, 0, 1, "Scanning the dataset...")
        # the cancel flag is read before every single file is copied, so
        # a cancelled staging stage stops within one image
        meta = dataset.stage_dataset(
            self.config.dataset_dir,
            self.staging_root,
            should_stop=lambda: self.cancel_requested,
        )
        if self.cancel_requested:
            return
        self.records = records_module.records_from_staging(
            self.staging_root, self.classes
        )
        counts = dict(meta.get("counts", {}))
        if counts.get("orphan_labels"):
            self.warnings.append(
                f'{counts["orphan_labels"]} label file(s) without an image '
                "were skipped",
            )
        if counts.get("unreadable_label_pairs"):
            self.warnings.append(
                f'{counts["unreadable_label_pairs"]} pair(s) with an '
                "unreadable label json were excluded (not staged and "
                "never validated)",
            )
        self._progress(
            STAGE_STAGING,
            1,
            1,
            f'Staged {counts.get("original", 0)} pair(s)',
        )
        self._emit_warnings(self.warnings)
        originals = [
            record
            for record in self.records
            if record.kind == records_module.KIND_ORIGINAL
        ]
        self.stage_finished.emit(STAGE_STAGING, len(originals))
        self.dataset_ready.emit(self.staging_root, self.records, meta)

    def _originals(self) -> List[ValidationRecord]:
        """Return every staged original record."""

        return [
            record
            for record in self.records
            if record.kind == records_module.KIND_ORIGINAL
        ]

    def _augment_sources(self) -> List[ValidationRecord]:
        """Return the originals that may receive augmented copies.

        An image without a label is staged as SKIPPED: it is never
        judged, therefore it never receives augmented copies either.
        """

        return [
            record
            for record in self.records
            if record.kind == records_module.KIND_ORIGINAL
            and record.verdict != records_module.SKIPPED
        ]

    def _augment_plan(self, sources: List[ValidationRecord]) -> List[int]:
        """Compute how many augmented copies every source gets."""

        config = self.config
        if not config.augment_enabled or not sources:
            return [0] * len(sources)
        validate_augment_params(config.augment_params)
        mode = config.augment_mode or DEFAULT_AUGMENT_MODE
        rng = None
        if mode == DEFAULT_AUGMENT_MODE:
            from .app_config import make_rng

            rng = make_rng(config.augment_params.seed, 0)
        return plan_aug_counts(
            len(sources),
            mode,
            multiplier=config.multiplier,
            ratio=config.ratio if config.ratio is not None else DEFAULT_RATIO,
            total=config.total_count,
            rng=rng,
        )

    def _augment_jobs(
        self, sources: List[ValidationRecord], plan: List[int]
    ) -> Iterator[_AugmentJob]:
        """Yield one job per augmented copy, in plan order.

        The ordinal of a job is its position in the plan. The seed of a
        sample comes from its sample index and its file names from the
        source relpath plus the copy index, so neither of them depends on
        the order in which the worker threads happen to run.
        """

        ordinal = 0
        for index, (record, count) in enumerate(zip(sources, plan)):
            if count <= 0:
                continue
            stem, ext = osp.splitext(osp.basename(record.relpath))
            for copy_index in range(1, int(count) + 1):
                yield _AugmentJob(
                    ordinal=ordinal,
                    record=record,
                    sample_index=index * 1000 + copy_index,
                    copy_index=copy_index,
                    image_name=f"{stem}_aug{copy_index}{ext}",
                    source_ext=ext,
                )
                ordinal += 1

    def _augment_one(self, job: _AugmentJob) -> _AugmentJobResult:
        """Generate one augmented copy (this runs on a worker thread).

        Every file is written by the thread owning the sample and no
        state is shared with the other jobs, therefore the outcome of a
        sample is the very same whatever the number of threads.
        """

        from .augment import (
            MAX_ATTEMPTS,
            augment_sample,
            augmented_relpath,
            decode_image,
            encode_image,
        )

        record = job.record
        if self.cancel_requested:
            # asked once per sample as well: a cancelled run stops the
            # samples that never started instead of finishing the stage,
            # and the empty result carries no warning at all
            return _AugmentJobResult(job=job)
        try:
            image = decode_image(record.staging_image_path)
        except Exception as error:  # noqa: BLE001
            image = None
            decode_error = error
        else:
            decode_error = None
        if image is None:
            detail = f": {decode_error}" if decode_error else ""
            return _AugmentJobResult(
                job=job,
                warnings=[
                    f"could not decode {record.relpath} for augmentation"
                    f"{detail}"
                ],
            )

        try:
            label = records_module.read_staging_label(record) or {}
            outcome = augment_sample(
                image,
                label,
                self.config.augment_params,
                job.sample_index,
                image_name=job.image_name,
            )
            if outcome is None:
                # no seed of this sample kept every shape inside the
                # canvas: the sample is dropped instead of being written
                # with a clipped or a vanished defect, and the whole
                # attempt budget of it is what it cost the stage
                return _AugmentJobResult(
                    job=job,
                    attempts=MAX_ATTEMPTS,
                    discarded=True,
                )
            data, target_ext, fallback = encode_image(
                outcome.image, job.source_ext
            )
            relpath = augmented_relpath(
                record.relpath, job.copy_index, target_ext
            )
            paths = dataset.staging_paths(
                self.staging_root, records_module.KIND_AUGMENTED, relpath
            )
            os.makedirs(osp.dirname(paths["image"]), exist_ok=True)
            with open(paths["image"], "wb") as handle:
                handle.write(data)
            outcome.label["imagePath"] = osp.basename(paths["image"])
            dataset.write_json(paths["label"], outcome.label)
        except Exception as error:  # noqa: BLE001
            # one broken sample is skipped and reported, exactly like an
            # image that cannot be decoded: the run keeps going
            return _AugmentJobResult(
                job=job,
                warnings=[
                    f"could not augment {record.relpath}: "
                    f"{type(error).__name__}: {error}"
                ],
            )

        child = records_module.make_record(
            records_module.KIND_AUGMENTED,
            relpath,
            paths["image"],
            paths["label"],
            source_display=record.source_display,
            parent_record_id=record.record_id,
        )
        grayscale = bool(getattr(outcome, "grayscale", False))
        child.aug_detail = {
            "parent_relpath": record.relpath,
            "copy_index": job.copy_index,
            "seed": int(self.config.augment_params.seed),
            # the try that really produced this copy: its own seed is
            # derived from (base seed, sample index, attempt) and is
            # recorded so the very copy can be reproduced on its own
            "attempt": int(outcome.attempt),
            "attempt_seed": int(outcome.seed),
            "attempts": int(outcome.attempts),
            # The fill of the uncovered canvas really used by this copy:
            # the fill has no option any more, so the fixed name is
            # recorded next to the seed (it is no official argument).
            "border_fill": BORDER_FILL,
            "clipped": outcome.clipped,
            "encode_fallback": bool(fallback),
            "type_counts": outcome.type_counts,
            "grayscale": grayscale,
        }
        return _AugmentJobResult(
            job=job,
            child=child,
            encode_fallback=bool(fallback),
            clipped=list(outcome.clipped),
            type_counts=dict(outcome.type_counts),
            grayscale=grayscale,
            attempts=int(outcome.attempts),
        )

    def _run_augment_jobs(
        self, jobs: Iterator[_AugmentJob], workers: int, total: int
    ) -> Tuple[Dict[int, _AugmentJobResult], int]:
        """Run the jobs on a thread pool and report the finished samples.

        Returns the results keyed by their plan ordinal plus the amount
        of samples the pool finished. Only a bounded window of jobs is in
        flight at once, so a cancelled run never waits for more than that
        window and the results of a cancelled run are dropped instead of
        being merged. The cancel flag is read before every submission and
        once per sample inside the worker (see _augment_one), so a click
        stops the stage within a sample. The progress counter follows the
        finished samples, the very semantics the serial loop had.
        """

        results: Dict[int, _AugmentJobResult] = {}
        window = max(workers * 2, workers + 1)
        queue = iter(jobs)
        exhausted = False
        pending: Dict[Future, _AugmentJob] = {}
        done = 0
        pool = ThreadPoolExecutor(
            max_workers=workers,
            thread_name_prefix="xal-augment",
            initializer=_opencv_initializer(workers),
        )
        try:
            while not exhausted or pending:
                while not exhausted and len(pending) < window:
                    if self.cancel_requested:
                        exhausted = True
                        break
                    try:
                        job = next(queue)
                    except StopIteration:
                        exhausted = True
                        break
                    pending[pool.submit(self._augment_one, job)] = job
                if not pending:
                    break
                finished = wait_futures(
                    list(pending), return_when=FIRST_COMPLETED
                )[0]
                for future in sorted(
                    finished, key=lambda item: pending[item].ordinal
                ):
                    job = pending.pop(future)
                    if self.cancel_requested:
                        continue
                    result = self._resolve_augment_result(future, job)
                    results[result.job.ordinal] = result
                    done += 1
                    self._progress(
                        STAGE_AUGMENT,
                        done,
                        max(total, 1),
                        f"Augmenting {done}/{total}",
                    )
        finally:
            # a cancelled run drops the samples that never started and
            # only waits for the ones already running
            pool.shutdown(wait=True, cancel_futures=True)
        return results, done

    @staticmethod
    def _resolve_augment_result(
        future: Future, job: _AugmentJob
    ) -> _AugmentJobResult:
        """Return the result of one job, degraded when the thread broke.

        The pool hands back the exception of a failed job; turning it
        into a warning keeps a single broken sample from failing the
        whole run.
        """

        try:
            return future.result()
        except Exception as error:  # noqa: BLE001
            detail = f"{type(error).__name__}: {error}"
            return _AugmentJobResult(
                job=job,
                warnings=[f"could not augment {job.record.relpath}: {detail}"],
            )

    def _stage_augment(self) -> None:
        """Generate the augmented children for every staged original.

        The samples are produced by a pool of threads (one job per
        augmented copy) running the fixed concurrency of the
        configuration; the children are appended to the run records in
        plan order once the pool is drained, so the produced files and
        the record order are the same for every thread count. Every
        thread of a parallel pool pins the OpenCV thread pool to a
        single thread before its first job.
        """

        # imported here like every other augment symbol of the module:
        # the stack is only paid for by a run that really augments
        from .augment import GRAYSCALE_PATH_NOTE

        sources = self._augment_sources()
        plan = self._augment_plan(sources)
        total = int(sum(plan))
        # the concurrency is fixed: the pool is the one count both
        # stages derive from the logical processors of this machine,
        # never a value a stored configuration could have kept
        workers = default_workers()
        summary: Dict[str, Any] = {
            "enabled": bool(self.config.augment_enabled),
            "mode": self.config.augment_mode,
            "seed": int(self.config.augment_params.seed),
            # The fill of the uncovered canvas, the same value every
            # child records in its own aug_detail: black, with no option.
            "border_fill": BORDER_FILL,
            "planned": total,
            "workers": workers,
            "augmentable_originals": len(sources),
            "skipped_no_label": len(self._originals()) - len(sources),
            "generated": 0,
            "failed": 0,
            # How many times a sample had to be generated again because a
            # try left a shape outside the canvas (a retry is a produced
            # sample that needed more than one attempt) and how many
            # samples no attempt could fit at all: a dropped sample is
            # neither written nor recorded.
            "retried": 0,
            "attempts_total": 0,
            "discarded_unfittable": 0,
            "discarded": [],
            "discarded_note": DISCARDED_NOTE,
            "encode_fallback": 0,
            # gray sources travel through the gray -> RGB -> gray path of
            # augment_sample: the counter says how many copies did
            "grayscale": False,
            "grayscale_images": 0,
            "grayscale_note": GRAYSCALE_PATH_NOTE,
            "clipped_shapes": 0,
            "type_counts": {},
            "clipped": [],
            "disabled_multi_image_augmentations": list(
                MULTI_IMAGE_AUGMENTATIONS
            ),
            "params": self.config.augment_params.snapshot(),
        }
        self.augment_summary = summary
        self._progress(STAGE_AUGMENT, 0, max(total, 1), "Augmenting images...")
        if not self.config.augment_enabled:
            self.stage_finished.emit(STAGE_AUGMENT, 0)
            return

        jobs = self._augment_jobs(sources, plan)
        results, done = self._run_augment_jobs(jobs, workers, total)
        if self.cancel_requested:
            return

        known = set(self.warnings)
        for ordinal in sorted(results):
            result = results[ordinal]
            for warning in result.warnings:
                if warning not in known:
                    known.add(warning)
                    self.warnings.append(warning)
            summary["attempts_total"] += int(result.attempts)
            child = result.child
            if child is None:
                if result.discarded:
                    summary["discarded_unfittable"] += 1
                    if len(summary["discarded"]) < DISCARDED_SAMPLE_LIMIT:
                        summary["discarded"].append(
                            {
                                "parent_relpath": result.job.record.relpath,
                                "copy_index": result.job.copy_index,
                                "attempts": int(result.attempts),
                            }
                        )
                else:
                    summary["failed"] += 1
                continue
            self.records.append(child)
            summary["generated"] += 1
            if int(result.attempts) > 1:
                summary["retried"] += 1
            if result.encode_fallback:
                summary["encode_fallback"] += 1
            if result.grayscale:
                summary["grayscale_images"] += 1
                summary["grayscale"] = True
            summary["clipped_shapes"] += len(result.clipped)
            if result.clipped:
                summary["clipped"].append(
                    {
                        "record_id": child.record_id,
                        "shapes": result.clipped,
                    }
                )
            for shape_type, amount in result.type_counts.items():
                bucket = summary["type_counts"]
                bucket[shape_type] = bucket.get(shape_type, 0) + amount
        self.stage_finished.emit(STAGE_AUGMENT, done)

    def _stage_infer(self) -> None:
        """Run ONNX inference and judge every record.

        The images are independent of each other, therefore they are
        dispatched over a pool of threads and every thread runs the whole
        per image work - decode, preprocess, session call, postprocess -
        on its own runner. The model itself cannot help: its batch is a
        fixed 1, so the only parallelism left is one session per thread,
        and the pool runs the fixed session count of the configuration.
        The verdicts are stored in plan order once the pool is drained,
        hence a record never depends on the order its image finished in.
        Every thread of a parallel pool pins the OpenCV thread pool to a
        single thread before its first job.
        """

        from .app_config import infer_session_threads
        from .inference import build_runner_pool

        # the session count is the very same fixed count as the augment
        # pool; the budget of one session is its slice of the machine
        workers = default_workers()
        intra_op, inter_op = infer_session_threads()
        # a zero budget means "keep what the runtime decides", which is
        # the configuration of a single session (nothing to share)
        budget = intra_op if intra_op > 0 else None
        try:
            # every runner owns its session; building them upfront pays
            # the load time once per worker instead of once per image
            runners = build_runner_pool(
                self.config.model_path,
                self.classes,
                workers,
                iou_threshold=self.config.iou_threshold,
                intra_op_threads=budget,
                inter_op_threads=inter_op if budget else None,
            )
        except Exception as error:  # noqa: BLE001
            raise ValidationConfigError(str(error)) from error
        runner = runners[0]
        self.model_info = runner.model_info()
        self.warnings.extend(runner.warnings)
        self._emit_warnings(runner.warnings)

        judge_augmented = bool(self.config.judge_augmented)
        pending = [
            record
            for record in self.records
            if record.kind == records_module.KIND_ORIGINAL
            and not record.deleted
            and record.verdict != records_module.SKIPPED
        ]
        if judge_augmented:
            pending += [
                record
                for record in self.records
                if record.kind == records_module.KIND_AUGMENTED
            ]
        else:
            for record in self.records:
                if record.kind == records_module.KIND_AUGMENTED:
                    record.verdict = records_module.NOT_JUDGED
                    record.detail = {
                        "not_judged": "judge_augmented is disabled"
                    }

        total = len(pending)
        self.infer_summary = {
            "workers": len(runners),
            "intra_op_threads": intra_op,
            "inter_op_threads": inter_op,
            "runtime_default_threads": intra_op == 0,
            "cpu_count": int(os.cpu_count() or 1),
            "images": total,
        }
        self._progress(STAGE_INFER, 0, max(total, 1), "Running inference...")
        jobs = (
            _InferJob(ordinal=index, record=record)
            for index, record in enumerate(pending)
        )
        results, _done = self._run_infer_jobs(jobs, runners, total)
        if self.cancel_requested:
            return
        # the records are judged in plan order, so the verdicts and their
        # progress line do not depend on the completion order
        for ordinal in sorted(results):
            self._apply_infer_result(results[ordinal])
        self.stage_finished.emit(STAGE_INFER, total)

    def _run_infer_jobs(
        self,
        jobs: Iterator[_InferJob],
        runners: List[Any],
        total: int,
    ) -> Tuple[Dict[int, _InferJobResult], int]:
        """Run the images on a thread pool and collect their verdicts.

        Every thread takes one runner for itself: the pool hands the
        runners out through a thread local, therefore an ONNX session is
        never used by two threads at once and no runner state is shared.
        Only a bounded window of images is in flight at once, so a
        cancelled run never waits for more than that window, stops
        submitting and drops the results it no longer needs. The cancel
        flag is read before every submission and once per image inside
        the worker (see _infer_one), so a click stops the stage within an
        image. The progress counter follows the finished images, the very
        same semantics the serial loop had.
        """

        results: Dict[int, _InferJobResult] = {}
        workers = len(runners)
        window = max(workers * 2, workers + 1)
        source = iter(jobs)
        exhausted = False
        pending: Dict[Future, _InferJob] = {}
        done = 0
        local = threading.local()
        available: SimpleQueue = SimpleQueue()
        for index in range(workers):
            available.put(index)

        initializer = _opencv_initializer(workers)

        def assign_runner() -> None:
            """Pin OpenCV, then give one private runner to this thread."""

            if initializer is not None:
                initializer()
            local.runner = runners[available.get()]

        def run_job(job: _InferJob) -> _InferJobResult:
            """Infer one image with the runner owned by this thread."""

            return self._infer_one(local.runner, job)

        pool = ThreadPoolExecutor(
            max_workers=workers,
            thread_name_prefix="xal-infer",
            initializer=assign_runner,
        )
        try:
            while not exhausted or pending:
                while not exhausted and len(pending) < window:
                    if self.cancel_requested:
                        exhausted = True
                        break
                    try:
                        job = next(source)
                    except StopIteration:
                        exhausted = True
                        break
                    pending[pool.submit(run_job, job)] = job
                if not pending:
                    break
                finished = wait_futures(
                    list(pending), return_when=FIRST_COMPLETED
                )[0]
                for future in sorted(
                    finished, key=lambda item: pending[item].ordinal
                ):
                    job = pending.pop(future)
                    if self.cancel_requested:
                        continue
                    results[job.ordinal] = future.result()
                    done += 1
                    self._progress(
                        STAGE_INFER,
                        done,
                        max(total, 1),
                        f"Inference {done}/{total}",
                    )
        finally:
            # a cancelled run drops the images that never started and
            # only waits for the ones already running
            pool.shutdown(wait=True, cancel_futures=True)
        return results, done

    def _infer_one(self, runner: Any, job: _InferJob) -> _InferJobResult:
        """Infer one image and judge it (this runs on a worker thread).

        The decode, the preprocessing, the session call and the
        postprocessing all happen here, and everything this thread
        touches belongs to the image it was given: the label file is
        read on its own, the shapes are built by the model of this
        thread and the verdict is computed from those two inputs only.
        A broken image becomes the INFER_ERROR verdict of its own record
        instead of an exception that would abort the whole run, exactly
        like the serial loop did.
        """

        if self.cancel_requested:
            # asked once per image as well: the images that never started
            # are dropped instead of being inferred for nothing
            return _InferJobResult(job=job)

        infer_error: Optional[str] = None
        predicted: List[Any] = []
        try:
            predicted = runner.predict(job.record.staging_image_path)
        except Exception as error:  # noqa: BLE001
            infer_error = str(error)

        if infer_error is not None:
            result = judge_record(
                [], [], self.classes, infer_error=infer_error
            )
            return _InferJobResult(
                job=job,
                verdict=result.verdict,
                reasons=list(result.reasons),
                detail=dict(result.detail),
            )

        label = records_module.read_staging_label(job.record)
        ground_truth = list((label or {}).get("shapes") or [])
        # The judge works one object at a time while the canvas draws one
        # box per object: a merged box is handed over once per class it
        # carries ("one box per class"), therefore every index of the
        # verdict (matched, false positives, low scores) lives in that
        # row coordinate system and pred_row_boxes maps a row back to the
        # payload box it came from.
        rows, row_boxes = expand_multilabel_rows(predicted)
        result = judge_record(
            ground_truth,
            rows,
            self.classes,
            ng_iou_threshold=self.config.ng_iou_threshold,
            ng_score_threshold=self.config.conf_threshold,
        )
        detail = dict(result.detail)
        detail["predicted_labels"] = [row["label"] for row in rows]
        detail["predicted_types"] = [row["shape_type"] for row in rows]
        detail["predictions"] = self._prediction_payload(predicted)
        detail["pred_row_boxes"] = row_boxes
        return _InferJobResult(
            job=job,
            verdict=result.verdict,
            reasons=list(result.reasons),
            detail=detail,
        )

    @staticmethod
    def _apply_infer_result(result: _InferJobResult) -> None:
        """Store the verdict of one image on its own record."""

        record = result.job.record
        record.verdict = result.verdict
        record.reasons = list(result.reasons)
        record.detail = dict(result.detail)
        record.judged = True

    @staticmethod
    def _prediction_payload(predicted: Any) -> List[Dict[str, Any]]:
        """Convert predicted shapes into JSON friendly dictionaries."""

        payload: List[Dict[str, Any]] = []
        for shape in predicted:
            points = []
            for point in getattr(shape, "points", []) or []:
                if hasattr(point, "x"):
                    points.append([float(point.x()), float(point.y())])
                else:
                    points.append([float(point[0]), float(point[1])])
            # a merged box carries one label per row of its group; the
            # two keys are only added when the shape really holds them,
            # so the payload of a single label prediction is unchanged
            if isinstance(shape, dict):
                labels = shape.get("labels")
                scores = shape.get("scores")
            else:
                labels = getattr(shape, "labels", None)
                scores = getattr(shape, "scores", None)
            entry = {
                "label": shape_label(shape),
                "shape_type": shape_type_of(shape),
                "points": points,
                "score": getattr(shape, "score", None),
            }
            if labels is not None:
                entry["labels"] = list(labels)
            if scores is not None:
                entry["scores"] = list(scores)
            payload.append(entry)
        return payload


__all__ = [
    "STAGE_AUGMENT",
    "STAGE_INFER",
    "STAGE_STAGING",
    "ValidationWorker",
]
